### ISSUE TITLE
bug(anthropic): Client doesn't work without temperature and max_tokens

### ISSUE THREAD

**Issue by faassen** [0xPlaygrounds/rig#65]
- [x] I have looked for existing issues (including closed) about this

## Bug Report

I kept getting a 400 error when I tried to make a request to Anthropic (incidentally printing the response body for that error would be very helpful to debug this). I couldn't get what I was doing wrong, until I finally figured out rig is sending a 'temperature' and 'max_tokens' as null, and Anthropic rejects the request if you do so.

Leaving *out* `temperature` and `max_tokens` works, but they cannot be null.

## Reproduction

```rust

    let api_key = std::env::var("ANTHROPIC_API_KEY").unwrap_or_default();

    let anthropic_client = anthropic::ClientBuilder::new(&api_key).build();

    let agent = anthropic_client
        .agent(anthropic::CLAUDE_3_5_SONNET)
        // without max tokens and temperature it won't work
        .max_tokens(1000)
        .temperature(1.0) 
        .build();

    // Prompt the model and print its response
    let response = agent
        .prompt("Who are you?")
        .await
        .expect("Failed to prompt Claude Sonnet");

    println!("Claude Sonnet: {response}");
```

## Expected behavior

I expect it to work without setting max_tokens and temperature explicitly. Either send the default temperature (1.0) and max_tokens (varies per model) or set these fields to undefined (if possible this would be simpler).

**Comment by faassen** [comment]
I don't see how to fix this with serde's `json!` macro, but if you had an explicit struct and constructed JSON from that, you can use skip serializing (https://serde.rs/attr-skip-serializing.html)

**Comment by 0xMochan** [comment]
Thanks for creating an issue!

I think having some reasonable defaults would be a good step to have in the library. The default for temperature should definitely be defined or not included in the request. For `max_tokens`, unfortuntely Anthropic needs this always defined and there's a different value for every model type. I think having a default for the specific model would be suitable but it would be brittle due to new models being released (since they all have different names).

**Comment by faassen** [comment]
Given that max tokens is required, the Anthropic builder should take it as either a required argument or build should fail with an error if it's not provided.

**Comment by cvauclair** [comment]
@faassen for some context, the primary goal of Rig was to define provider-agnostic constructs for building LLM powered apps, `Agent` being one of those constructs. As such, we define a standardized `CompletionRequest` model that can be populate using the `AgentBuilder`. However, the latter is not aware of the specific requirements of each provider, and when one provider requires a parameter that others do not (as is the case with `max_tokens`), this puts us in a tricky situation: we don't want to require the parameter for all providers, but we still want to have some validation in case where the user decides to use an Anthropic model. We also do not want to add some provider-specific behavior in the `Agent` (we do not want something like: `if self.model.provider == "Anthropic" {do_something}`).

That said, there might be a way to make this work since the `Agent` is parametrized by a type `M` which must implements `CompletionModel`. The `CompletionModel` trait already has a `Response` associated type which can be used to get the full provider-specific response. We could also add a `Request` associated type to the `CompletionModel` trait, which would allow the `Agent<M: CompletionModel>` to validate the parameters when calling `build()` using the `M::Request` type.

This however is a pretty significant change and would make integration slightly more complicated, so for now #67, which adds some Anthropic-specific validation before sending the request in the `provider::anthropic::Client` is a good enough solution.

Curious to know your thoughts about all this, and thanks for the feedback :smile:
